#!/usr/bin/env bash

function abspath {
  python -c 'import sys, os; print(os.path.abspath(sys.argv[1]))' "$1"
}

docker run \
  --dns 192.168.0.1 \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --publish 8000:8080 \
  --entrypoint /bin/bash \
  -it \
  docker-proxy
